### PR TITLE
'Pause on failed loop' now works as expected

### LINKED ISSUE #53: Last action repeat counts as failed loop
I use "Pause on failed loop" to find when a change I have made to my action list result in a list that cannot be completed, rather than as a method of pausing at the end of runs.

The following circumstances appear to count as a 'failed loop', when that would not seem to me to count!  This therefore has the same functionality as "Pause before restart" in every circumstance that I have experienced.

+ "Pause on failed loop" - Checked
+ "Repeat last action on list" - Checked
+ Specified number of actions completed - I.e. if last action is to be completed 3 times, then it has been completed at least three times
+ Last use of that action does not complete because mana runs out

My suggestion would be that as long as item three is satisfied (i.e. the minimum number of repeats have been completed) that this doesn't count as a failed run.

Alternative solution - tooltip to specify what a 'failed loop' actually counts as.

### PR DESCRIPTION
**Pull request by super-aardvark**
Fixed an issue when 'Keep current list active' and 'Repeat last action on list' are used together

Fixed some formatting issues

Fixes #53

### CODE REVIEW

File: loops/driver.js [hunk 1]
```diff
@@ -123,7 +123,9 @@ function pauseGame(ping) {
 function prepareRestart() {
     const curAction = actions.getNextValidAction();
     if (options.pauseBeforeRestart ||
-        (options.pauseOnFailedLoop && actions.current.filter(action => action.loopsLeft > 0).length > 0)) {
+        (options.pauseOnFailedLoop && 
+         (actions.current.filter(action => action.loopsFailed > 0).length > 0 ||
```
Comment (omsi6) [inline loops/driver.js:127]: Is the `loopsFailed` really needed here? If you fail an action, the action will always have at least 1 loop left since you either couldn't finish the last loop, or were never able to start the action in the first place. I could be missing something though.

Comment (super-aardvark) [reply loops/driver.js:127]: actions.getNextValidAction does this when an action fails due to wrong zone or missing resources:
```
            curAction.loopsFailed = curAction.loopsLeft;
            curAction.loopsLeft = 0;
```
So checking loopsLeft wouldn't catch it.  I guess we could delete that and skip the loopsFailed check...
